### ISSUE TITLE
[Bug]: RedisInsight Database keeps growing because of load balancer http healthchecks

### ISSUE THREAD

**Issue by oguzhanaygn** [RedisInsight/RedisInsight#1022]
**Preconditions** (Any important steps we need to know)
RedisInsight deployed to AWS EKS with `/db` path mounted to AWS EFS, there is Application Load Balancer in front of it.

**Steps to reproduce** (How to reproduce what you found step by step)
Deploy EFS CSI Driver
Deploy Application Load Balancer Controller
Deploy RedisInsight on Kubernetes with containers `/db` path mounted to EFS.
Attach ALB to RedisInsight k8s Service
Enable HTTP Healthchecks for RedisInsight

**Actual behavior** (A short description of what you found)
In database **(redisinsight.db)**, there are entries like below because of healthcheck requests when I dump the db with `sqlite3`; 
```
INSERT INTO django_session VALUES('q5xonz38vrmmhw867on484369sg6erv0','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNspA:SmI_uqzXfJVfyi_bXvAyx5DxQUUKAdvzgBTOJ2XgpfE','2022-08-30 09:25:24.502415');
INSERT INTO django_session VALUES('qt268tfiz7vqp2f71ovikdzvqiyeilr9','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNspA:SmI_uqzXfJVfyi_bXvAyx5DxQUUKAdvzgBTOJ2XgpfE','2022-08-30 09:25:24.667504');
INSERT INTO django_session VALUES('29f173ctsjwyk8jxilcww3edypvmmecz','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNspP:C2etRFi7ktiYuV3VP1g2KL7ryq4a-hwbE9OJ1QA-d5E','2022-08-30 09:25:39.917301');
INSERT INTO django_session VALUES('ooeb9fx91bjbz4i4vo7553k5oz1jqu61','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNspP:C2etRFi7ktiYuV3VP1g2KL7ryq4a-hwbE9OJ1QA-d5E','2022-08-30 09:25:39.712689');
INSERT INTO django_session VALUES('rg7h9lz3evc90djwhfg2io3i2zzq68xc','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNspe:L6hLlS1ApbHLNnxoPPVKY_09SGGBw9KIx4e4c-k1-7g','2022-08-30 09:25:54.697414');
INSERT INTO django_session VALUES('stvx7h24a14xgsp2347lceu4yjc2qgnx','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNspe:L6hLlS1ApbHLNnxoPPVKY_09SGGBw9KIx4e4c-k1-7g','2022-08-30 09:25:54.868489');
INSERT INTO django_session VALUES('8oquvywtf1l22h2wfc21atgzcot0xyof','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNspt:5g6WrIaXvwtxtBJTNulGoQ3UhKiv3NElVkByhqTM9fo','2022-08-30 09:26:09.805824');
INSERT INTO django_session VALUES('n529jhji7tia7y34x8u4n1yiydq6v05n','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNspt:5g6WrIaXvwtxtBJTNulGoQ3UhKiv3NElVkByhqTM9fo','2022-08-30 09:26:09.881043');
INSERT INTO django_session VALUES('sntq6pti26u67799c4uvmajm97n6jme6','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNsq8:unFRYArYktq0xdqgbyH9Vx7aOBAbatbdTP9h0yeI3iM','2022-08-30 09:26:24.882577');
INSERT INTO django_session VALUES('pfrtycirz2prnxoiukp5gbejhg1wx67x','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNsq8:unFRYArYktq0xdqgbyH9Vx7aOBAbatbdTP9h0yeI3iM','2022-08-30 09:26:24.810698');
INSERT INTO django_session VALUES('pdzba1ey8w5imctqsj2pwegb7aovro7u','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNsqN:Vfx4GAfmFgb9ifeTwBokDNXTd3R2_fpud5HU-wSgfbc','2022-08-30 09:26:39.896415');
INSERT INTO django_session VALUES('f6j1en37jb0bsbryaw80q9mf8uvnr1ju','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNsqN:Vfx4GAfmFgb9ifeTwBokDNXTd3R2_fpud5HU-wSgfbc','2022-08-30 09:26:39.816716');
INSERT INTO django_session VALUES('3v091ksbfdp21v8klimnx201d3iffvps','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNsqc:ndS4Rj-RYOmqY0rhfS82j99WUTd6dGIWjiHqmSHNLLo','2022-08-30 09:26:54.613349');
INSERT INTO django_session VALUES('04d3avmo3jo9m6jn5lysh50208wlj9rp','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNsqc:ndS4Rj-RYOmqY0rhfS82j99WUTd6dGIWjiHqmSHNLLo','2022-08-30 09:26:54.891687');
INSERT INTO django_session VALUES('ug5dz95ogi7x866cuyr603zajehg63j7','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNsqr:mX65yXpJeTfBKw648HmtAenxiaNwnz_LkqQPYmiikTs','2022-08-30 09:27:09.782043');
INSERT INTO django_session VALUES('7n2heu8qatb42vdldgvbgls8h3m3hpwc','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNsqs:baKCW597I7MbghJU4TKPfyggKx1XaNv-1UiihxpZyFI','2022-08-30 09:27:10.073340');
INSERT INTO django_session VALUES('zty2saupwi66qtp67u1bvjcres2pfqau','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNsr6:NQWoDfnIvjZx99fXWN2tw0bEdGKOQCy34Yvp3HkNG6A','2022-08-30 09:27:24.780791');
INSERT INTO django_session VALUES('ouqa9tfl4x9fro8kivc02qurgh9eax8m','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNsr6:NQWoDfnIvjZx99fXWN2tw0bEdGKOQCy34Yvp3HkNG6A','2022-08-30 09:27:24.936125');
INSERT INTO django_session VALUES('wk3aq4piv9z938593izjpq8otqrnis9i','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNsrL:va6HU_a3RyST_jMCXyHJid75mlgGHvF4tzKuX_htQD8','2022-08-30 09:27:39.795869');
INSERT INTO django_session VALUES('yjsdfo0nmoy7vyx1zf0lwih8uk9389o7','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNsrM:twlw32GW_zRAV-ByC3qt2euC_X7c3cWOvtokgtDDvoE','2022-08-30 09:27:40.072285');
INSERT INTO django_session VALUES('y54sxr0sdfvggmhmgwk63mkc9r8frcf4','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNsra:NCZvy-iPrzQ8AAZXc6vypt6F-TlM7WfJAUPbc5IZpg8','2022-08-30 09:27:54.825921');
INSERT INTO django_session VALUES('tmyvkpwibww91oeqpmqgaxtket7s2vv9','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNsra:NCZvy-iPrzQ8AAZXc6vypt6F-TlM7WfJAUPbc5IZpg8','2022-08-30 09:27:54.993605');
INSERT INTO django_session VALUES('gsoryvgu4p6fi9czijilia4xws68lpu7','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNsrp:T7NYI4KvN6lqYffytUqBqOo8QD8rJ1CFFus4e-TJylM','2022-08-30 09:28:09.656683');
INSERT INTO django_session VALUES('ox5xkvyj2sneemagjiismewm9kf7ncxo','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNsrp:T7NYI4KvN6lqYffytUqBqOo8QD8rJ1CFFus4e-TJylM','2022-08-30 09:28:09.911438');
INSERT INTO django_session VALUES('4rapswn2w6mytcuhguq4sk3bpnh9163m','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNss4:-A-mWn7MxEpFNwy6xErtuYvvRyvsvM6Vf_66EvNBtSI','2022-08-30 09:28:24.846371');
INSERT INTO django_session VALUES('lxm9z8fxu8e712sl70prpsxkmj9mv4cr','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNss4:-A-mWn7MxEpFNwy6xErtuYvvRyvsvM6Vf_66EvNBtSI','2022-08-30 09:28:24.919547');
INSERT INTO django_session VALUES('d8aixuhdca55xo58b0u24wwwhxg0fj9u','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNssJ:u1FJ2DmfBzwSCWsyx2ZC48c0u_p4OBx2SdPRHalBKVY','2022-08-30 09:28:39.852430');
INSERT INTO django_session VALUES('ksxlsawui7t0tw51xblxv2vg1e4rsum3','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNssJ:u1FJ2DmfBzwSCWsyx2ZC48c0u_p4OBx2SdPRHalBKVY','2022-08-30 09:28:39.782133');
INSERT INTO django_session VALUES('v64bz02vs1r8r65j061nzqjbl4jucd14','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNssY:hD2BgSPTnkbCmhOTR6UX8evCeK_KPRdwO8gnoHVtlNs','2022-08-30 09:28:54.872537');
INSERT INTO django_session VALUES('yvyy251fuy1jps446di4v7v8pjieu7ew','.eJxVjDsOwjAQBe_iGlle4i8lfc5grb0bHEC2FCcV4u4QKQW0b2beS0Tc1hK3zkucSVwEiNPvljA_uO6A7lhvTeZW12VOclfkQbscG_Hzerh_BwV7-daDhkxsFEOwCScXBgfGg_JmcooUQs6U1cDn4DWrpJEw2aDZgtHaJC_eH9iXN5c:1oNssY:hD2BgSPTnkbCmhOTR6UX8evCeK_KPRdwO8gnoHVtlNs','2022-08-30 09:28:54.947130');
```
In my AWS ALB healthcheck config, internal is 15 second and two requests are being sent to RedisInsight be considered healthy. This HTTP healthcheck request is causing both `/db` & related EFS path to grow unnecessarily because of all `django_session` data is written to the DB path.

**Expected behavior**

Healthcheck path requests shouldn't be considered sessions, or sessions shouldn't be kept directly in  `/db` path or **(redisinsight.db)** file.
Additionally, maybe session logs can be excluded with an environment variable.

Versions & YAML

AWS EKS 1.21
redisinsight:1.12.1
aws-efs-csi-driver:v1.3.6

Deployment YAML
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight-prod
  namespace : xxx
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: redisinsight-prod
  template:
    metadata:
      labels:
        owner: XXX
        app: redisinsight-prod
    spec:
      containers:
      - name:  redisinsight-prod
        image: redislabs/redisinsight:1.12.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: db
          mountPath: /db
        ports:
        - containerPort: 8001
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 100Mi
        env:
        - name: RIHOST
          value: "0.0.0.0"
        - name: RILOGLEVEL
          value: "ERROR"
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: redisinsight-prod-efs-claim
 ```

**Comment by GnaneshKunal** [comment]
Hey @oguzhanaygn ,

We have worked fixing this and have the debug build handy, would it be possible for you to verify the fix?

Here's the debug docker image:
```
redislabs/redisinsight:disable-django-session-healthcheck
```

**Comment by oguzhanaygn** [comment]
Hi @GnaneshKunal , thank you very much for your response, I will be trying it, after the trial, I'll share my impressions about the fix. Appreciate it :)

**Comment by oguzhanaygn** [comment]
Hi @GnaneshKunal , I tried debug image and it didn't work. It's still writing django sessions to `redisinsight.db` and data is still growing up. Here is my new YAML;

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight-beta
  namespace : xxx
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 10%
    type: RollingUpdate
  selector:
    matchLabels:
      app: redisinsight-beta
  template:
    metadata:
      labels:
        owner: xxx
        app: redisinsight-beta
    spec:
      containers:
      - name:  redisinsight-beta
        image: redislabs/redisinsight:disable-django-session-healthcheck
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: db
          mountPath: /db
        ports:
        - containerPort: 8001
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 100Mi
        env:
        - name: RILOGLEVEL
          value: "ERROR"
        - name: RITRUSTEDORIGINS
          value: "xxx"
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: redisinsight-beta-efs-claim
```
