### ISSUE TITLE
Wrong content type header when subpath is defined.

### ISSUE THREAD

**Issue by mikurth** [RedisInsight/RedisInsight#1232]
As soon as i define a subpath redis does no longer load up. Even if I acces it directly withou revers proxy. Tried  it docker latest and oct 22 fixes container.

Problem: The browser blocks the execution of the java script (chrome) due to wrong MIME type. From chrome consol:

`Refused to execute script from 'https://[my_domain]/apps/redisinsight/static/app/bundle.7efcec36bb875e95d308.js' because 
its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

and from the network tab all the response headers:

cache-control: max-age=0, no-cache, no-store, must-revalidate, private
content-length: 694
**content-type: text/html; charset=utf-8**
cross-origin-opener-policy: same-origin
date: Mon, 03 Oct 2022 20:28:46 GMT
expires: Mon, 03 Oct 2022 20:28:46 GMT
feature-policy: camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';
referrer-policy: same-origin
set-cookie: csrftoken=gmvh1OJXu7Jv6H3pCbBxApS71uYTUuY96WoM3vNDa2RYEH2TFtKidmcIBplNtOtL; expires=Mon, 02 Oct 2023 20:28:46 GMT; Max-Age=31449600; Path=/; SameSite=Lax
strict-transport-security: max-age=63072000; includeSubDomains; preload
vary: Cookie
x-content-type-options: nosniff
x-frame-options: allow-from https:[my domain]
x-robots-tag: none,noarchive,nosnippet,notranslate,noimageindex,
x-xss-protection: 1; mode=block

as soon as i disable the subpath the mime type response is content-type: text/javascript; charset="utf-8". all headers:

access-control-allow-origin: *
cache-control: max-age=315360000, public, immutable
content-encoding: gzip
content-length: 6001936
**content-type: text/javascript; charset="utf-8"**
cross-origin-opener-policy: same-origin
date: Mon, 03 Oct 2022 17:27:10 GMT
etag: "63061cdf-100c2eb"
feature-policy: camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';
last-modified: Wed, 24 Aug 2022 12:43:11 GMT
referrer-policy: same-origin
vary: Accept-Encoding
x-content-type-options: nosniff
x-frame-options: allow-from https:[my domain]
x-robots-tag: none,noarchive,nosnippet,notranslate,noimageindex,
x-xss-protection: 1; mode=block

_Originally posted by @mikurth in https://github.com/RedisInsight/RedisInsight/issues/258#issuecomment-1265854117_

**Comment by ViktarStarastsenka** [comment]
@mikurth , please check another thread - https://github.com/RedisInsight/RedisInsight/issues/258#issuecomment-1345529921
re-open the issue if it is still relevant.

**Comment by ur-gh** [comment]
Guys I have same exact issue - as mentioned in https://github.com/RedisInsight/RedisInsight/issues/258#issuecomment-1625633617
ANy idea what was the resolution?

**Comment by joelsonjunior** [comment]
I had the exact same problem using Traefik as reverse proxy, I could get it to work by removing the proxy prefix before forwarding the request. With Traefik this can easily be done using the stripprefix middleware.
I'm not sure about the "how" it works though... 

```yaml
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: "redisinsight"
    environment:
      - RILOGLEVEL=DEBUG
      - RIPROXYENABLE=True
      - RIPROXYPATH=/redisinsight
    labels:
      - "traefik.http.services.redisinsight.loadbalancer.server.port=8001"
      - "traefik.http.routers.redisinsight.middlewares=redisinsight-stripprefix"
      - "traefik.http.middlewares.redisinsight-stripprefix.stripprefix.prefixes=/redisinsight"
```
