### ISSUE TITLE
[Bug]: Cannot POST /api/instance

### ISSUE THREAD

**Issue by collabnix** [RedisInsight/RedisInsight#1299]
I am able to connect to the default 6379 Redis instance via RedisInsight. But when I am starting a Redis instance on port 6380, it doesn't work.

##Please Note:
 If I download RedisInsight manually from the official site, it works perfectly. The issue is only with Docker image

1. Install RedisInsight using Redis stack Docker Image

```
services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - redisnet
    volumes:
      - redisinsight_db:/db
    networks:
      - redisnet

volumes:
  redisinsight_db: 
  
  
networks:
  redisnet:
```

2. Bring up the Redis Stack

```
docker compose up -d 
```

3.  Verify if Redis Stack Docker container is up and running

```
docker compose ps
NAME                                    COMMAND             SERVICE             STATUS              PORTS
redisinsight-docker-extension-redis-1   "/entrypoint.sh"    redis               running             0.0.0.0:6379->6379/tcp, 0.0.0.0:8001->8001/tcp
 
```

4. Access RedisInsight

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/34368930/196677880-089279eb-5b10-4b8e-800a-b5413240029a.png">

4. Run another instance of Redis on port 6380

```
docker run -d -p 6380:6379 redis
```

5. Connect via RedisInsight

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/34368930/196677758-b5e513d5-dc50-4b79-b316-419b1b465ef4.png">

It throws error saying "Cannot POST /api/instance"
