### ISSUE TITLE
[Bug]: Wrong content type header set for java scripts when a subpath is defined

### ISSUE THREAD

**Issue by mikurth** [RedisInsight/RedisInsight#1300]
**Preconditions** (Any important steps we need to know)
Start the docker container :latest with following environment variables:
      - RIPROXYENABLE=t                        # Enable Subpath Proxy
      - RIPROXYPATH=${RIPROXYPATH:-/redisinsight/}        # Set static proxy subpath

**Steps to reproduce** (How to reproduce what you found step by step)
Start up the RedisInsight container with the env. Variables as shown above and image latest / 1.13.0. Query the web page while running the developer options on chrome or edge. You will see only a white page. When inspecting it in the console you will find following information:

**Actual behavior** (A short description of what you found)
The browser does not execute the java script as the mime type provided by the server is wrong. See devloper option consol in chrome:
"Refused to execute script from 'https://[my_domain]/redisinsight/static/app/bundle.7efcec36bb875e95d308.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled."

**Expected behavior** (A short description of what you expected to find)
the mime / content type should be: content-type: text/javascript; charset="utf-8". Which is set when there is no subpath defined.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
image: redislabs/redisinsight:latest #or 1.13.0 - the build is very old. Maybe it just requires a new build!? I did not try to build the image myselfe...

**Comment by GnaneshKunal** [comment]
Hey @mikurth,

Can you once check the response of `https://[my_domain]/redisinsight/static/app/bundle.7efcec36bb875e95d308.js`? The error might be due to that the path is blocked (due to some proxy) and it returns a non javascript response for that path.

Also is the domain set properly?

**Comment by GnaneshKunal** [comment]
Can you send the traefik config? And are you hosting RedisInsight in a Subpath?

Can you check how to set the subpath proxy correctly from this sample Nginx example - https://github.com/RedisInsight/RedisInsight-reverse-proxy/tree/main/nginx-subpath-proxy

**Comment by tasiotas** [comment]
same here with Caddy as proxy. Are you saying it works with nginx?

**Comment by kyleli666** [comment]
Have the same issue here, but somehow solved after I rewrite the uri before sending to redisinsight.
RIPROXYPATH set to /redisinsight
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: redisinsight-vs
  namespace: manage-tool
spec:
  gateways:
    - shared/portal-gw
  hosts:
    - "*"
  http:
    - name: redisinsight
      match:
        - uri:
            prefix: /redisinsight
      rewrite:
        uri: /
      route:
        - destination:
            host: redisinsight-service.manage-tool.svc.cluster.local
```

**Comment by ViktarStarastsenka** [comment]
@mikurth , please re-open the ticket if the issue is still relevant.

**Comment by joelsonjunior** [comment]
I had the exact same problem using Traefik as reverse proxy, I could get it to work by removing the proxy prefix before forwarding the request. With Traefik this can easily be done using the stripprefix middleware.
I'm not sure about the "how" it works though... 

```yaml
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: "redisinsight"
    environment:
      - RILOGLEVEL=DEBUG
      - RIPROXYENABLE=True
      - RIPROXYPATH=/redisinsight
    labels:
      - "traefik.http.services.redisinsight.loadbalancer.server.port=8001"
      - "traefik.http.routers.redisinsight.middlewares=redisinsight-stripprefix"
      - "traefik.http.middlewares.redisinsight-stripprefix.stripprefix.prefixes=/redisinsight"
```

**Comment by dawescc** [comment]
## 2025 v2.6+, Caddy Reverse Proxy

### compose.yml

```yml

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    environment:
      RIPROXYENABLE: True
      RI_PROXY_PATH: "/redisinsight"
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    networks:
      - {your-docker-network}

```

### Caddyfile

```Caddyfile

        /* Optional: trailing slash redirects domain.com/redisinsight to domain.com/redisinsight/ */

	@redisinsight_no_slash path /redisinsight
	redir @redisinsight_no_slash /redisinsight/ 308

	handle /redisinsight/* {
		reverse_proxy http://redisinsighti:5540 {
			header_up Host {http.request.host}
		}
	}

```
