### ISSUE TITLE
[Bug]: Proxying to service redis/redis-stack with subpath behind loadbalancer

### ISSUE THREAD

**Issue by Synertry** [RedisInsight/RedisInsight#1937]
**Description** (Describe the issue)
Using _redis/redis-stack_ connecting to RedisInsight via proxy through a virtual IP does not serve up content -> The site is blank.
A decoupled config with _redis/redis-stack-server_ and standalone _redislabs/redisinsight_ does work with slight modifications for the VIP, as demonstrated here:
https://github.com/RedisInsight/RedisInsight-reverse-proxy/tree/main/nginx-subpath-proxy
mentioned here:
https://github.com/RedisInsight/RedisInsight/issues/258#issuecomment-1345529921

**tl;dr**
Essentially proxying to service redis/redis-stack with subpath without exposing RIPORT externally does not work.

**Steps to reproduce** (How to reproduce what you found step by step)
Use any folder and drop these 3 files in there:

- env:
```conf
COMPOSE_PROJECT_NAME=redis
```

- compose.yaml:
```yaml
networks:
    netRedis:
        name: netRedis
        attachable: true

services:
    stack:
        image: redis/redis-stack:6.2.6-v6
        networks:
            - netRedis
        volumes:
            - ./data:/data
            - ./db:/db
        environment:
            - RILOGLEVEL=DEBUG
            - RITRUSTEDORIGINS=* # Development only
            - RIPROXYENABLE=t
            - RIPROXYPATH=/redisinsight/
            # - RIPROXYPREFIX=X-Forwarded-Prefix

    proxy:
        image: nginx:1.23.4-alpine
        volumes: 
            - ./nginx.conf.template:/etc/nginx/templates/redis.conf.template
        ports:
            - '80:80'
        environment:
            - NGINX_PORT=80
            - NGINX_SERVER_NAME=redis.local
            - NGINX_PROXY_PATH=/redisinsight/
            - NGINX_PROXY_PASS=http://redis-stack-1:8001 # Compose service name
        command:
        - sh
        - -c
        - |
            printf "Visit <a href=\"$$NGINX_PROXY_PATH\">$$NGINX_PROXY_PATH</a> for redisinsight" > /etc/nginx/index.html
            /docker-entrypoint.sh nginx -g "daemon off;"
        depends_on:
            - stack
        networks:
            - netRedis
```

- nginx.conf.template:
```nginx
server {
    listen ${NGINX_PORT};
    server_name ${NGINX_SERVER_NAME};

    error_log /dev/stdout debug;
    access_log /dev/stdout;

    root /etc/nginx;
    index index.html;

    location ${NGINX_PROXY_PATH} {
        proxy_pass             ${NGINX_PROXY_PASS};
        proxy_read_timeout     900;
        proxy_set_header       Host $host;
        proxy_set_header       X-Forwarded-Prefix ${NGINX_PROXY_PATH};
    }
}
```

**Actual behavior** (A short description of what you found)
A blank page on path _/redisinsight/_  (see screenshots below)

<details>
  <summary>Logs from Nginx</summary>
  
```sh
redis-proxy-1  | 192.168.16.1 - - [10/Apr/2023:21:56:31 +0000] "GET /redisinsight/ HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
redis-proxy-1  | 2023/04/10 21:56:32 [error] 37#37: *1 open() "/etc/nginx/main.b4b5491f098433429b58.css" failed (2: No such file or directory), client: 192.168.16.1, server: redis.local, request: "GET /main.b4b5491f098433429b58.css HTTP/1.1", host: "redis.local", referrer: "http://redis.local/redisinsight/"
redis-proxy-1  | 192.168.16.1 - - [10/Apr/2023:21:56:32 +0000] "GET /main.b4b5491f098433429b58.css HTTP/1.1" 404 555 "http://redis.local/redisinsight/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
redis-proxy-1  | 2023/04/10 21:56:32 [error] 37#37: *1 open() "/etc/nginx/js/bundle.964.min.js" failed (2: No such file or directory), client: 192.168.16.1, server: redis.local, request: "GET pleWebKit/537.36 (KHTML, like Gecko) pleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
redis-proxy-1  | 2023/04/10 21:56:32 [error] 37#37: *6 open() "/etc/nginx/js/bundle.elasticVendor.min.js" failed (2: No such file or directory), client: 192.168.16.1, server: redis.local, request: "GET /js/bundle.elasticVendor.min.js HTTP/1.1", host: "redis.local", referrer: "http://redis.local/redisinsight/"
redis-proxy-1  | 192.168.16.1 - - [10/Apr/2023:21:56:32 +0000] "GET /js/bundle.elasticVendor.min.js HTTP/1.1" 404 555 "http://redis.local/redisinsight/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
redis-proxy-1  | 2023/04/10 21:56:32 [error] 37#37: *5 open() "/etc/nginx/js/bundle.monacoVendor.min.js" failed (2: No such file or directory), client: 192.168.16.1, server: redis.local, request: "GET /js/bundle.monacoVendor.min.js HTTP/1.1", host: "redis.local", referrer: "http://redis.local/redisinsight/"
redis-proxy-1  | 192.168.16.1 - - [10/Apr/2023:21:56:32 +0000] "GET /js/bundle.monacoVendor.min.js HTTP/1.1" 404 555 "http://redis.local/redisinsight/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
redis-proxy-1  | 2023/04/10 21:56:32 [error] 37#37: *1 open() "/etc/nginx/js/bundle.main.min.js" failed (2: No such file or directory), client: 192.168.16.1, server: redis.local, request: "GET /js/bundle.main.min.js HTTP/1.1", host: "redis.local", referrer: "http://redis.local/redisinsight/"
redis-proxy-1  | 192.168.16.1 - - [10/Apr/2023:21:56:32 +0000] "GET /js/bundle.main.min.js HTTP/1.1" 404 555 "http://redis.local/redisinsight/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
redis-proxy-1  | 2023/04/10 21:56:35 [error] 37#37: *1 open() "/etc/nginx/main.b4b5491f098433429b58.css" failed (2: No such file or directory), client: 192.168.16.1, server: redis.local, request: "GET /main.b4b5491f098433429b58.css HTTP/1.1", host: "redis.local", referrer: "http://redis.local/redisinsight/"
redis-proxy-1  | 192.168.16.1 - - [10/Apr/2023:21:56:35 +0000] "GET /main.b4b5491f098433429b58.css HTTP/1.1" 404 555 "http://redis.local/redisinsight/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
```
  
</details>

<details>
  <summary>Chrome Dev Tools Console</summary>
  
  ```http
redis.local/:1          GET http://redis.local/main.b4b5491f098433429b58.css net::ERR_ABORTED 404 (Not Found)
redis.local/:1          GET http://redis.local/js/bundle.reactVendor.min.js net::ERR_ABORTED 404 (Not Found)
redis.local/:1          GET http://redis.local/js/bundle.monacoVendor.min.js net::ERR_ABORTED 404 (Not Found)
redis.local/:1          GET http://redis.local/js/bundle.runtime.min.js net::ERR_ABORTED 404 (Not Found)
redis.local/:1          GET http://redis.local/js/bundle.elasticVendor.min.js net::ERR_ABORTED 404 (Not Found)
redis.local/:1          GET http://redis.local/js/bundle.utilityVendor.min.js net::ERR_ABORTED 404 (Not Found)
redis.local/:1          GET http://redis.local/js/bundle.964.min.js net::ERR_ABORTED 404 (Not Found)
redis.local/:1          GET http://redis.local/js/bundle.main.min.js net::ERR_ABORTED 404 (Not Found)
  ```
  
</details>

**Expected behavior** (A short description of what you expected to find)
The RedisInsight webpage.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://user-images.githubusercontent.com/60792595/231008400-8f7a229e-4d82-4bd8-abc1-b809ff8eb9c6.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
OS: Ubuntu 22.04.2 (VMWare and WSL2)
Docker images:
- [6.2.6-v6](https://hub.docker.com/layers/redis/redis-stack/6.2.6-v6/images/sha256-7eab80573807fbc1a8eb7873a3d6c4da391cc38154148076557fe4bd10ab9a55)
- [edge](https://hub.docker.com/layers/redis/redis-stack/edge/images/sha256-5afc95c307131699443e6a8ee65c73c80782e8d3e04170c0e51aea2bc5410161)

Current workaround is proxying path / directly to RIPORT:
```nginx
    location / {
        proxy_pass             ${NGINX_PROXY_PASS};
        # ... other proxy settings
    }
```
