### ISSUE TITLE
Subpath setting not working

### ISSUE THREAD

**Issue by ur-gh** [RedisInsight/RedisInsight#2289]
I am having same saubpath issues as mentioned ticket 258 - in chrome dev cnosole. I am adding {BASEURL}/rui subpath. Not sure if I should open the new ticket. If inappropriate please close this ticket.

Refused to execute script from '{BASEURL}/rui/static/app/bundle.a9e99f96c044971b8537.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

Here is script tag in Index.html
<script defer="defer" src="/rui/static/app/bundle.a9e99f96c044971b8537.js"></script>

As you can see there is no type="text/javascript" in the script tag above and hence the chrome error. 
Could we reopen the ticket? I am using kubernetes but following similar settings conceptualy for static subpath.

My set up : 
I have set env variables like so in my helm chart for /rui as subpath.
            - name: "RILOGLEVEL"
              value: "DEBUG"
            - name: "RIPROXYPATH"
              value: "/rui"
            - name: "RIPROXYENABLE"
              value: "t"

And my ingress as Prefix /rui forwarding to my redis service.

Everything works fine as soon as I remove /rui settings above and on the default root path in the URL

_Originally posted by @ur-gh in https://github.com/RedisInsight/RedisInsight/issues/258#issuecomment-1625633617_

**Comment by ur-gh** [comment]
I have now tried with synamic sub pathtoo but due to other issue related to logging, it is unlear whether redis insight got the header needed for dynamic sub path. I continue to have multiple issues here. Please help

**Comment by ur-gh** [comment]
Also justo be clear, I am using the latest Docker image from https://hub.docker.com/r/redislabs/redisinsight/tags

**Comment by joelsonjunior** [comment]
I had the same exact problem using Traefik as reverse proxy, I could get it to work by removing the proxy prefix before forwarding the request. With Traefik this can easily be done using the stripprefix middleware.
I'm not sure about the "how" it works though... 

```yaml
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: "redisinsight"
    environment:
      - RILOGLEVEL=DEBUG
      - RIPROXYENABLE=True
      - RIPROXYPATH=/redisinsight
    labels:
      - "traefik.http.services.redisinsight.loadbalancer.server.port=8001"
      - "traefik.http.routers.redisinsight.middlewares=redisinsight-stripprefix"
      - "traefik.http.middlewares.redisinsight-stripprefix.stripprefix.prefixes=/redisinsight"
```
