### ISSUE TITLE
[Bug]: Can't connect to cluster within Docker

### ISSUE THREAD

**Issue by thx01138** [RedisInsight/RedisInsight#2735]
**Preconditions** 
Create a cluster inside docker.

```yaml
#compose.yml
version: '3'

networks:
  redis-cluster-compose:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  redis-node-0:
    image: arm64v8/redis:7
    ports:
      - "7000:7000"
    networks:
      redis-cluster-compose:
        ipv4_address: 172.20.0.30
    hostname: redis-node-0
    volumes:
      - ./7000:/redis
    command: redis-server /redis/redis.conf
  redis-node-1:
    image: arm64v8/redis:7
    ports:
      - "7001:7001"
    networks:
      redis-cluster-compose:
        ipv4_address: 172.20.0.31
    hostname: redis-node-1
    volumes:
      - ./7001:/redis
    command: redis-server /redis/redis.conf
  redis-node-2:
    image: arm64v8/redis:7
    ports:
      - "7002:7002"
    networks:
      redis-cluster-compose:
        ipv4_address: 172.20.0.32
    hostname: redis-node-2
    volumes:
      - ./7002:/redis
    command: redis-server /redis/redis.conf
  redis-node-3:
    image: arm64v8/redis:7
    ports:
      - "7003:7003"
    networks:
      redis-cluster-compose:
        ipv4_address: 172.20.0.33
    hostname: redis-node-3
    volumes:
      - ./7003:/redis
    command: redis-server /redis/redis.conf

  redis-cluster-creator:
    image: arm64v8/redis:7
    ports:
      - "6999:6999"
    networks:
      - redis-cluster-compose
    command: redis-cli -p 7000 --cluster create redis-node-0:7000 redis-node-1:7001 redis-node-2:7002 redis-node-3:7003  --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
```

```properties
#7000/redis.conf (repeat and update port for 7001-7003)
 port 7000
 cluster-enabled yes
 cluster-config-file nodes.conf
 cluster-node-timeout 5000
 appendonly yes
 bind 0.0.0.0
```

**Steps to reproduce** 
Attempt to connect to `localhost:7000` from RedisInsight.

**Actual behavior** 
Error: The connection has timed out, please check the connection details.

**Expected behavior** 
RedisInsight starts successfully.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://github.com/RedisInsight/RedisInsight/assets/9137386/8848b769-d39c-4fa8-9b6b-a33f7f2638a1)

**Additional context** 
Cluster is successful and very performant on M1 MacBookPro.  I am able to connect via JedisCluster with a HostAndPortMapper implemented thusly:
```java
            DefaultJedisClientConfig.builder()
                .resp3()
                .hostAndPortMapper(this::mapHostAndPort)
                .build()
```
and
```java
    public HostAndPort mapHostAndPort(HostAndPort hap){
        if(hap.getHost().equals("localhost")){
            return hap;
        }
        //LOGGER.info(hap);
        return new HostAndPort("localhost", hap.getPort());
    }
```

Basically the crux of the issue seems to be that the cluster is only capable of sharing the docker-internal IP addresses which the host OS can't make sense of.  This can be overcome with the HostAndPortMapper provided as the ports are the same on the internal docker network and the machine itself.  If a mapper could be configured for a connection within RedisInsight then I suspect it could connect. 

I am able to telnet to port 7000. (Above configuration files are simplified as I'm actually running 16 master nodes right now but that is immaterial.)

```
~ telnet localhost 7000
Trying ::1...
Connected to localhost.
Escape character is '^]'.
CLUSTER NODES
$1800
3b0417b6c1e7685f543f785cd0f28243b87ee1e6 172.20.0.36:7006@17006 master - 0 1698689042529 7 connected 6144-7167
a097632e96d0e397440e03bd37eb0d758e520949 172.20.0.38:7008@17008 master - 0 1698689042000 9 connected 8192-9215
22914b449242e8ec42daaf5d0d4cddbbcb1acdc0 172.20.0.32:7002@17002 master - 0 1698689042000 3 connected 2048-3071
7b29dd805e79742f491a1677b8d2469be3038268 172.20.0.33:7003@17003 master - 0 1698689043139 4 connected 3072-4095
068804da44d0863cf081a76370a4f35fc0b8246b 172.20.0.42:7012@17012 master - 0 1698689042000 13 connected 12288-13311
3746289087c2cf86581c936be3a92ca781cfb69e 172.20.0.44:7014@17014 master - 0 1698689042528 15 connected 14336-15359
8d198a510b861a60ec8c51aefce43f00b335cfd6 172.20.0.31:7001@17001 master - 0 1698689042010 2 connected 1024-2047
c7d75eee722ba4fbf84744e9a05b27615f04d57b 172.20.0.40:7010@17010 master - 0 1698689042529 11 connected 10240-11263
e92ba639440e1c8cadaed05a681ddce4a2749f9e 172.20.0.39:7009@17009 master - 0 1698689043000 10 connected 9216-10239
8b29e831b394dc30a3adb25cef1807fba8418642 172.20.0.34:7004@17004 master - 0 1698689041000 5 connected 4096-5119
76f3e311f72b3037d2b06fd4d7e42c61a2c34e39 172.20.0.30:7000@17000 myself,master - 0 1698689041000 1 connected 0-1023
a580f1a2d23e67f43678e09381884eda62553bd3 172.20.0.43:7013@17013 master - 0 1698689043035 14 connected 13312-14335
9fa824948b7754030cbca3a8980125a07d61c931 172.20.0.37:7007@17007 master - 0 1698689042000 8 connected 7168-8191
ba3abffdb95e63aac7307f7452d08509a1ecd200 172.20.0.45:7015@17015 master - 0 1698689043139 16 connected 15360-16383
9f16ee7d37886c0d562a2df6091c97775b2f8615 172.20.0.41:7011@17011 master - 0 1698689041000 12 connected 11264-12287
0e71ad072fa3e180f831e2e842ac984771dc982a 172.20.0.35:7005@17005 master - 0 1698689042528 6 connected 5120-6143

QUIT
+OK
Connection closed by foreign host.
```

**Logs** (note: 3s timeout was set)
10/30/2023, 2:06:54 PM | INFO | SettingsService | Getting application settings. | {"stack":[]}
10/30/2023, 2:06:54 PM | INFO | DatabaseService | Testing new database connection | {"stack":[]}
10/30/2023, 2:06:54 PM | INFO | SettingsService | Succeed to get application settings. | {"stack":[]}
10/30/2023, 2:06:54 PM | INFO | RedisConnectionFactory | Successfully connected to the redis database | {"stack":[]}
10/30/2023, 2:06:57 PM | ERROR | ConnectionMiddleware | The connection has timed out, please check the connection details. POST /api/databases/test | {"stack":[{}]}
10/30/2023, 2:06:58 PM | ERROR | RedisConnectionFactory | Server closed the connection. | {"stack":[{}]}
10/30/2023, 2:06:58 PM | ERROR | DatabaseFactory | Failed to add oss cluster. | {"stack":[{"message":"Server closed the connection."}]}
10/30/2023, 2:06:58 PM | ERROR | DatabaseService | Connection test failed | {"stack":[{"message":"Server closed the connection."}]}
