### ISSUE TITLE
[Feature Request]: Allow adding default database through environment variables

### ISSUE THREAD

**Issue by jz222** [RedisInsight/RedisInsight#289]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

I would like to deploy Redis Insight as a stateless service on Google Cloud Run behind an oAuth proxy. Since there can't be a state, the settings for the connected Redis databases get lost and you have to add them every time you enter Redis Insight.

**How often do you encounter this problem** (Describe how frequently this problem occurs).

This is a general problem, that prevents me from easily deploying Redis Insights.

**Alternatives considered** (Describe any alternative features or products you've considered).

I understand that more than just the database connections are stored, but it would already help a lot if you could provide the Redis host and port as environment variables and if provided, it adds this database automatically when the Redis Insight container starts up instead of adding the database through the Redis Insight UI.

**Comment by pzh6** [comment]
Thats a great idea, but i think that it would be better to add some sort of an optional config file (perhaps configmap if used with k8s).
That way you could also initiate multiple database connections at once.

**Comment by kostacasa** [comment]
Interested in the exact same use case! The nice thing about environment variables is that cloud secrets can be mapped as variables to cloud run containers natively so passwords could be set in a secure fashion.

**Comment by GnaneshKunal** [comment]
Hi @jz222 


We currently have two ways to alternative ways to add a database to RedisInsight V1:
- Via GET URL - https://docs.redis.com/latest/ri/using-redisinsight/api-get/
  - Adding the database using URL parameters.
- Via POST URL - https://docs.redis.com/latest/ri/using-redisinsight/api/
  - You would be needed to write a script and that script must be run in an instance (or redisinsight instance itself) where its possible to hit redisinsight.

### For trying to add via GET,
Try to maybe bookmark a URL like "https://my-awesome-domain.com/add/name=redisacl&host=172.19.0.2&port=6379&username=myuser&password=p1pp0" and hit it when the state gets deleted.

### For trying to add via POST
try:
Something like this in docker compose:
```
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    networks:
      - redis-microservices-network
    depends_on:
      - app-redis
    restart: always
  
  redis-insight-setup:
    image: curlimages/curl
    command: >
           -s -vvv -X "POST" "http://redis-insight:8001/api/instance/"  
           -H "Content-Type: application/json; charset=utf-8" 
           -d '{"host": "app-redis","name": "redis","connectionType": "STANDALONE","port": 6379}'     
    networks:
      - redis-microservices-network
    depends_on:
      - redis-insight
      - app-redis
    restart: "on-failure"
```


And something like this in K8s:
```
# RedisInsight service with name 'redisinsight-service'
apiVersion: v1
kind: Service
metadata:
  name:
    redisinsight-service # name should not be 'redisinsight'
    # since the service creates
    # environment variables that
    # conflicts with redisinsight
    # application's environment
    # variables `REDISINSIGHT_HOST` and
    # `REDISINSIGHT_PORT`
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8001
  selector:
    app: redisinsight
---
# RedisInsight deployment with name 'redisinsight'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight #deployment name
  labels:
    app: redisinsight #deployment label
spec:
  replicas: 1 #a single replica pod
  selector:
    matchLabels:
      app: redisinsight #which pods is the deployment managing, as defined by the pod template
  template: #pod template
    metadata:
      labels:
        app: redisinsight #label for pod/s
    spec:
      containers:
        - name: redisinsight #Container name (DNS_LABEL, unique)
          image: redislabs/redisinsight:latest #repo/image
          imagePullPolicy: IfNotPresent #Always pull image
          volumeMounts:
            - name: db #Pod volumes to mount into the container's filesystem. Cannot be updated.
              mountPath: /db
          ports:
            - containerPort: 8001 #exposed container port and protocol
              protocol: TCP
          env:
            - name: REDIS_SSL
              value: "TRUE"
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redb-movie-database
                  key: port
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redb-movie-database
                  key: service_name
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redb-movie-database
                  key: password
            - name: REDIS_GRAPH_PORT
              valueFrom:
                secretKeyRef:
                  name: redb-graph-movie-database
                  key: port
            - name: REDIS_GRAPH_HOST
              valueFrom:
                secretKeyRef:
                  name: redb-graph-movie-database
                  key: service_name
            - name: REDIS_GRAPH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redb-graph-movie-database
                  key: password
            - name: REDIS_SEARCH_PORT
              valueFrom:
                secretKeyRef:
                  name: redb-search-movie-database
                  key: port
            - name: REDIS_SEARCH_HOST
              valueFrom:
                secretKeyRef:
                  name: redb-search-movie-database
                  key: service_name
            - name: REDIS_SEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redb-search-movie-database
                  key: password
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  curl -s -vvv -X "POST" "http://localhost:8001/api/instance/" -H "Content-Type: application/json; charset=utf-8" -d '{"host": "'"${REDIS_HOST}"'","name": "movie-database","connectionType": "STANDALONE","port": '"${REDIS_PORT}"',"password": "'"${REDIS_PASSWORD}"'","tls":{"useTls": true,"clientAuth": false, "verifyServerCert": false }}' 
                  curl -s -vvv -X "POST" "http://localhost:8001/api/instance/" -H "Content-Type: application/json; charset=utf-8" -d '{"host": "'"${REDIS_SEARCH_HOST}"'","name": "search-movie-database","connectionType": "STANDALONE","port": '"${REDIS_SEARCH_PORT}"',"password": "'"${REDIS_SEARCH_PASSWORD}"'","tls":{"useTls": true,"clientAuth": false, "verifyServerCert": false }}'
                  curl -s -vvv -X "POST" "http://localhost:8001/api/instance/" -H "Content-Type: application/json; charset=utf-8" -d '{"host": "'"${REDIS_GRAPH_HOST}"'","name": "graph-movie-database","connectionType": "STANDALONE","port": '"${REDIS_GRAPH_PORT}"',"password": "'"${REDIS_GRAPH_PASSWORD}"'","tls":{"useTls": true,"clientAuth": false, "verifyServerCert": false }}'
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 5
      volumes:
        - name: db
          emptyDir: {} # node-ephemeral volume https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
```

**Comment by anu-kailash** [comment]
> And something like this in K8s:
> 
> ```
> # RedisInsight service with name 'redisinsight-service'
> apiVersion: v1
> kind: Service
> metadata:
>   name:
>     redisinsight-service # name should not be 'redisinsight'
>     # since the service creates
>     # environment variables that
>     # conflicts with redisinsight
>     # application's environment
>     # variables `REDISINSIGHT_HOST` and
>     # `REDISINSIGHT_PORT`
> spec:
>   type: LoadBalancer
>   ports:
>     - port: 80
>       targetPort: 8001
>   selector:
>     app: redisinsight
> ---
> # RedisInsight deployment with name 'redisinsight'
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: redisinsight #deployment name
>   labels:
>     app: redisinsight #deployment label
> spec:
>   replicas: 1 #a single replica pod
>   selector:
>     matchLabels:
>       app: redisinsight #which pods is the deployment managing, as defined by the pod template
>   template: #pod template
>     metadata:
>       labels:
>         app: redisinsight #label for pod/s
>     spec:
>       containers:
>         - name: redisinsight #Container name (DNS_LABEL, unique)
>           image: redislabs/redisinsight:latest #repo/image
>           imagePullPolicy: IfNotPresent #Always pull image
>           volumeMounts:
>             - name: db #Pod volumes to mount into the container's filesystem. Cannot be updated.
>               mountPath: /db
>           ports:
>             - containerPort: 8001 #exposed container port and protocol
>               protocol: TCP
>           env:
>             - name: REDIS_SSL
>               value: "TRUE"
>             - name: REDIS_PORT
>               valueFrom:
>                 secretKeyRef:
>                   name: redb-movie-database
>                   key: port
>             - name: REDIS_HOST
>               valueFrom:
>                 secretKeyRef:
>                   name: redb-movie-database
>                   key: service_name
>             - name: REDIS_PASSWORD
>               valueFrom:
>                 secretKeyRef:
>                   name: redb-movie-database
>                   key: password
>             - name: REDIS_GRAPH_PORT
>               valueFrom:
>                 secretKeyRef:
>                   name: redb-graph-movie-database
>                   key: port
>             - name: REDIS_GRAPH_HOST
>               valueFrom:
>                 secretKeyRef:
>                   name: redb-graph-movie-database
>                   key: service_name
>             - name: REDIS_GRAPH_PASSWORD
>               valueFrom:
>                 secretKeyRef:
>                   name: redb-graph-movie-database
>                   key: password
>             - name: REDIS_SEARCH_PORT
>               valueFrom:
>                 secretKeyRef:
>                   name: redb-search-movie-database
>                   key: port
>             - name: REDIS_SEARCH_HOST
>               valueFrom:
>                 secretKeyRef:
>                   name: redb-search-movie-database
>                   key: service_name
>             - name: REDIS_SEARCH_PASSWORD
>               valueFrom:
>                 secretKeyRef:
>                   name: redb-search-movie-database
>                   key: password
>           readinessProbe:
>             exec:
>               command:
>                 - sh
>                 - -c
>                 - |
>                   curl -s -vvv -X "POST" "http://localhost:8001/api/instance/" -H "Content-Type: application/json; charset=utf-8" -d '{"host": "'"${REDIS_HOST}"'","name": "movie-database","connectionType": "STANDALONE","port": '"${REDIS_PORT}"',"password": "'"${REDIS_PASSWORD}"'","tls":{"useTls": true,"clientAuth": false, "verifyServerCert": false }}' 
>                   curl -s -vvv -X "POST" "http://localhost:8001/api/instance/" -H "Content-Type: application/json; charset=utf-8" -d '{"host": "'"${REDIS_SEARCH_HOST}"'","name": "search-movie-database","connectionType": "STANDALONE","port": '"${REDIS_SEARCH_PORT}"',"password": "'"${REDIS_SEARCH_PASSWORD}"'","tls":{"useTls": true,"clientAuth": false, "verifyServerCert": false }}'
>                   curl -s -vvv -X "POST" "http://localhost:8001/api/instance/" -H "Content-Type: application/json; charset=utf-8" -d '{"host": "'"${REDIS_GRAPH_HOST}"'","name": "graph-movie-database","connectionType": "STANDALONE","port": '"${REDIS_GRAPH_PORT}"',"password": "'"${REDIS_GRAPH_PASSWORD}"'","tls":{"useTls": true,"clientAuth": false, "verifyServerCert": false }}'
>             initialDelaySeconds: 10
>             periodSeconds: 5
>             timeoutSeconds: 10
>             failureThreshold: 5
>       volumes:
>         - name: db
>           emptyDir: {} # node-ephemeral volume https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
> ```

redislabs/redisinsight:1.12.0 does not have curl for the readinessProbe though

**Comment by GnaneshKunal** [comment]
Hey @anu-kailash, 

`1.12.1` has curl version. Please check that out.

**Comment by TheOneReeve** [comment]
Are the responses here still the solution for this feature request, or has there been an update to use environment variables to set default database connection?

**Comment by ViktarStarastsenka** [comment]
hi @TheOneReeve , we have plans to add an option of setting default databases through environment variables, though I can't say the exact release (I think in a couple of months or so).

**Comment by jz222** [comment]
Thank you @ViktarStarastsenka I'm also still very interested to see this feature so that we can use Redis Insight without a database. I will make adoption and deployments much easier and reduce maintenance efforts.

**Comment by HelmerBarcos** [comment]
I had to use the `PATCH` method and the `/api/databases/redis-stack` endpoint. Please adjust the `depends_on`, `networks`, and environment variables for your specific configurations.

```
  redisdb-setup:
    image: curlimages/curl
    environment:
      REDIS_PORT: '${REDIS_PORT:-6379}'
      REDIS_STACK_DATABASE_NAME: My Redis DB
    command: >
      -s -vvv -X "PATCH" "http://CONTAINER_NAME_OR_HOST:$REDIS_GUI_PORT/api/databases/redis-stack"  
      -H "Content-Type: application/json; charset=utf-8" 
      -d '{"host": "localhost", "name": "$REDIS_STACK_DATABASE_NAME", "port": $REDIS_PORT}'
    depends_on:
      - the_redis_container
    restart: 'on-failure'
    networks:
      - your_network
```

**Comment by drivebyer** [comment]
```
containerPort: 5540
```
Works for me.

**Comment by shanproofpoint** [comment]
in case anyone is struggling with this. in the latest redisinsight docker , the following works

`            URI uri = URI.create("http://localhost:5540/api/databases");
            String requestBody = """
                            {
                              "name": "redis7000",
                              "host": "redis",
                              "port": 7000
                            }
                            """;


            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);`

**Comment by drivebyer** [comment]
Hi @shanproofpoint, when I request `curl -s -X POST http://localhost:5540/api/databases/ -H "Content-Type: application/json; charset=utf-8" -d "{\"host\":\"$REDIS_HOST\", \"name\":\"default\", \"port\": $REDIS_PORT}"`, I received an error:

```
{"message":"Failed to authenticate, please check the username or password.","error":"Unauthorized","statusCode":401}
```

It appears that we need to include a password when adding a database. How did you manage to succeed without a password?

**Comment by shanproofpoint** [comment]
@drivebyer my redis didnt need a username and password. you can include "username" and "password" in the json as well

**Comment by Pierre-Hugues** [comment]
Hi,
For anyone looking to apply this workaround, with the sidecar container, but still having issues, here is what I had to do : 

```yaml
command:
  - "/bin/sh"
  - "-c"
args:
  - |
    set -euo pipefail
    sleep 30s
    curl -s -vvv -X "PATCH" "http://localhost:5540/api/settings" \
    -H "Content-Type: application/json; charset=utf-8" \
    -d '{"agreements":{"analytics":false,"notifications":false,"encryption":false,"eula":true}}'
    curl -s -vvv -X "POST" "http://localhost:5540/api/databases/" \
    -H "Content-Type: application/json; charset=utf-8" \
    -d '{"host": "'${REDIS_HOST}'","name": "redis","port": '${REDIS_PORT}',"username": "'${REDIS_USERNAME}'","password": "'${REDIS_PASSWORD}'","compressor": "NONE","ssh": false,"tls":true,"verifyServerCert":false}'
    (while true; do sleep 1; done)
```

some details : 
- `set -euo pipefail` => to make the container crash in case any of the curl goes wrong
- `sleep 30s` => in order to wait for redisinsight to be up and ready
- `curl -s -vvv -X "PATCH" "http://localhost:5540/api/settings"` => this was needed prior to add a database. Going through the front, it about the agreements you must accept in the popup.
- `(while true; do sleep 1; done)` => so the sidecar stays up and running - without this part, it would have kept restarting

Hope this helps until we have a better solution to import a database at startup 👍🏻

**Comment by jrlost** [comment]
my $0.02 running in k8s without a sidecar or readinessProbe (which will run constantly through the lifespan of the container).

This is what I'm using to setup my local dev environment
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: redisinsight
  labels:
    app: redisinsight

spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
        - name: redisinsight
          image: redislabs/redisinsight:latest
          ports:
            - containerPort: 5540
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  wget -q -O - --header="Content-Type:application/json" --post-data='{"name":"redis-local1","host":"redis","port":6379,"db":0,"compressor":"NONE","timeout":30000,"ssh":false,"tls":false}' http://127.0.0.1:5540/api/databases
            failureThreshold: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
```

Obviously you wouldn't need to pass things in directly and could do so via environment variables as everyone above has illustrated.  This just simply relies on the existing wget installation since the posted json is simple enough to work with wget. It also uses the new startupProbe which doesn't run past startup (unlike the readinessprobe).

Anyways, this is working well for me and I figured I'd share and add to the conversation.
