### ISSUE TITLE
[Bug]: Failed to initialize keytar module, redis/redisinsight docker container 2.44 arm

### ISSUE THREAD

**Issue by gretchenfrage** [RedisInsight/RedisInsight#3165]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)

On an M2 mac, running Debian ARM server in a VM through UTM, and then in that Debian VM, using docker compose to run the container as such:

```yml
  insight:
    #image: "redislabs/redisinsight:latest"
    image: "redis/redisinsight:latest"
    container_name: insight
    ports:
      - "8001:8001"
    volumes:
      - ../redisinsight:/db
    depends_on:
      - redis
```

TCP connections to the container fail, and `tail /data/logs/redisinsight-errors-2024-03-15.log.0` within the container reveal:

```
3/15/2024, 4:34:52 PM | ERROR | KeytarEncryptionStrategy | Failed to initialize keytar module | {"stack":[{"message":"Error loading shared library libsecret-1.so.0: No such file or directory (needed by /usr/src/app/redisinsight/api/node_modules/keytar/build/Release/keytar.node)"}]}
```

I am attempting to set up a learning environment as per [[this repo]](https://github.com/jphaugla/redisJupyter). Originally it was using the `redislabs/redisinsight` image but I switched it to the `redis/redisinsight` image, I don't know the difference between them but they fail in the exact same way.

**Actual behavior** (A short description of what you found)

Redisinsight docker container fails to initialize and fails to accept TCP connections.

**Expected behavior** (A short description of what you expected to find)

Redisinsight docker container initializes happily and serves web traffic on TCP connections.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

Please see steps to reproduce.
