### ISSUE TITLE
Error: failed to generate container "xxx" spec: failed to generate spec: failed to mkdir "/data": mkdir /data: read-only file system

### ISSUE THREAD

**Issue by cyberstackover** [RedisInsight/RedisInsight#3383]
hello, I found a problem with an error like this in Kubernetes. this is my yaml

**redisinsight.yaml**
```
apiVersion: v1
kind: Service
metadata:
  name: redisinsight-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5540
  selector:
    app: redisinsight

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisinsight-pv-claim
  labels:
    app: redisinsight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standart

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  labels:
    app: redisinsight
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      volumes:
        - name: redisinsight
          persistentVolumeClaim:
            claimName: redisinsight-pv-claim
      initContainers:
        - name: init
          image: busybox
          command:
            - "sh"
            - "-c"
            - "mkdir -p /data && chown -R 1000 /data"
          resources: {}
          volumeMounts:
            - name: redisinsight
              mountPath: /data
      containers:
        - name: redisinsight
          image: redis/redisinsight:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: redisinsight
              mountPath: /data
          ports:
            - containerPort: 5540
              protocol: TCP
```

redisinsight-pv.yaml

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redisinsight-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standart
  hostPath:
    path: "/data"
```

error :
> Warning  Failed             5m18s                 kubelet             Error: failed to generate container "63b59189270b2d2da9498dd08c5de3de4311afc23380c15b55dff7b4eca5aa90" spec: failed to generate spec: failed to mkdir "/data": mkdir /data: read-only file system

**Comment by GnaneshKunal** [comment]
Hey @cyberstackover,


The reason could be that the directory mounting the /data folder doesn't have storage space, or you need more permissions. Please mount the path in locations where you have enough space and permissions.

Also, there needs to be a typo in the persistent volume definition. The storage class name should be "standard".


If you already use a cloud provider, we recommend using one of the available storage mediums. For example, you can use AWS EBS or GCE persistent disks.

#### AWS EBS:

```yaml
# aws-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redisinsight-aws-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: <your-volume-id>
    fsType: ext4
```

#### GCE Persistent Disks:
```yaml
# gcp-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redisinsight-gcp-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: redisinsight-disk
    fsType: ext4
```
