### ISSUE TITLE
[Bug]: Cluster do not see slave or master nodes

### ISSUE THREAD

**Issue by spagu** [RedisInsight/RedisInsight#3450]
**Preconditions** docker-cluster of 7.2.5 installed of 3 master nodes only on 3 different servers. 

docker-compose.yml:
```yml
service:
  rediscluster:
    image: ${REDIS_IMAGE_NAME:-redis:7.2.5-alpine}
    ports:
      - 6383:6383
      - 16383:16383
    command: redis-server /usr/local/etc/redis/redis.conf --protected-mode no
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
 ```

redis.conf
```conf
port 6383
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly no
protected-mode no
maxmemory 30GB
maxmemory-policy allkeys-lru
databases 1
supervised auto
save ""
```

`redis-cli --cluster create 10.152.0.245:6383 10.152.2.1:6383 10.152.2.2:6383 --cluster-yes`

**Steps to reproduce** 
connect to one of the IP addresses By adding new database:
go to the analysis tool section,

**Actual behavior** (A short description of what you found)

see only a single A node

**Expected behavior** (A short description of what you expected to find)

see A,B,C nodes

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://github.com/RedisInsight/RedisInsight/assets/10611281/08e0f892-a678-411b-bdcd-e52bf96a161e)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Docker Redis 7.2.5 ( Ubuntu 22.04 )
Redis Insight 2.50.0
Windows 11
