### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by gadonski** [RedisInsight/RedisInsight#4435]
**Preconditions** (Any important steps we need to know)

i've made a deployment with persistent storage following these docs https://redis.io/docs/latest/operate/redisinsight/install/install-on-k8s/ but throws an error on deploy:
Error from server (BadRequest): container "redisinsight" in pod "redisinsight-6c5d6564f5-5fkqh" is waiting to start: PodInitializing

**Steps to reproduce**

I only changed the SC name:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisinsight-pv-claim
  labels:
    app: redisinsight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: redis
  name: redisinsight
  labels:
    app: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      volumes:
        - name: redisinsight
          persistentVolumeClaim:
            claimName: redisinsight-pv-claim
      initContainers:
        - name: init
          image: busybox
          command:
            - /bin/sh
            - '-c'
            - |
              chown -R 1000 /data
          resources: {}
          volumeMounts:
            - name: redisinsight
              mountPath: /data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      containers:
        - name:  redisinsight #Container name (DNS_LABEL, unique)
          image: redis/redisinsight:latest #repo/image
          imagePullPolicy: IfNotPresent #Always pull image
          volumeMounts:
          - name: redisinsight #Pod volumes to mount into the container's filesystem. Cannot be updated.
            mountPath: /data
          ports:
          - containerPort: 5540 #exposed container port and protocol
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: redis
  name: redisinsight-service
spec:
  #type: ClusterIP
  ports:
    - port: 80
      targetPort: 5540
  selector:
    app: redisinsight

---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: redis
  name: redis-ingress
  annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$2$3$4
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /redis(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: redisinsight-service
                port: 
                  number: 80
 
```

**Actual behavior** (A short description of what you found)

Defaulted container "redisinsight" out of: redisinsight, init (init)
Error from server (BadRequest): container "redisinsight" in pod "redisinsight-6c5d6564f5-5fkqh" is waiting to start: PodInitializing

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

![Image](https://github.com/user-attachments/assets/9e2cb821-c6e4-4324-ba27-101986db7592)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
