### ISSUE TITLE
Unable to import JSON config for redis connections

### ISSUE THREAD

**Issue by rcheng-roadie** [RedisInsight/RedisInsight#4571]
redisinsight-config.json works when manually inputted. `RI_PRE_SETUP_DATABASES_PATH` doesn't seem to be working on this version. I also have tried version 2.68 which doesn't even allowed manually inputing a JSON file.

Confirmed that the volume is mounted and the env variable exist in the pod. 
The only log is `Running docker-entry.sh`. This may suggest I need a different entry point to dynamically load in this json.

```
      volumes:
        - name: preload-config
          secret:
            secretName: redisinsight-config
      containers:
        - name: redisinsight
          image: "redis/redisinsight:2.42"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-ui
              containerPort: 5540
              protocol: TCP
          volumeMounts:
            - name: preload-config
              mountPath: /db/redisinsight-config.json
              subPath: redisinsight-config.json
          env:
            - name: RI_PRE_SETUP_DATABASES_PATH
              value: /db/redisinsight-config.json
```

Example redisinsight-config.json
```
[
      {
        "host": "master.asdf.usw2.cache.amazonaws.com",
        "port": 6379,
        "name": "some_api_3",
        "username": "",
        "password": "asdf_df",
        "database": 0,
        "ssl": true
      },
      {
        "host": "master.asdf.usw2.cache.amazonaws.com",
        "port": 6379,
        "name": "some_api",
        "username": "",
        "password": "asdf",
        "database": 1,
        "ssl": true
      },
      {
        "host": "master.asdf.usw2.cache.amazonaws.com",
        "port": 6379,
        "name": "some_api_2",
        "username": "",
        "password": "asf",
        "database": 0,
        "ssl": true
      }
]

```
