### ISSUE TITLE
[Bug]: Cannot add redis cluster in redisinsight:v2.0.4-preview

### ISSUE THREAD

**Issue by moluzhui** [RedisInsight/RedisInsight#483]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)
1. I run a redisinsight container builded by the v2.0.4-preview tag on github
2. I have no problem adding a single instance of redis created by docker
3. add redis cluster created by [bitnami-docker-redis-cluster](https://github.com/bitnami/bitnami-docker-redis-cluster/blob/master/docker-compose.yml) failed

**Actual behavior** (A short description of what you found)
I can't connect either one using `redisinsightv2.0.4-preview`. error is
```
{
    "statusCode": 400,
    "message": "Could not connect to <ip>:<port>, please check the connection details.",
    "error": "Bad Request"
}
```

**Expected behavior** (A short description of what you expected to find)
add redis cluster successfully and view all container of redis cluster

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://user-images.githubusercontent.com/44611938/161374350-75268fe4-2060-43b0-aae9-b89509117075.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
- OS: centos7
- redisinsight version is v2.0.4-preview
- redis cluster compose
```
cat docker-compose.yml
version: '2'
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    ports:
      - "8001:6379"
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    ports:
      - "8002:6379"
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    ports:
      - "8003:6379"
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    ports:
      - "8004:6379"
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
    ports:
      - "8005:6379"
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    ports:
      - "8006:6379"
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local
```
