### ISSUE TITLE
[Bug]:cannot run CLI or other operations behind https, since v1.12.1

### ISSUE THREAD

**Issue by kyleli666** [RedisInsight/RedisInsight#879]
**Preconditions** (Any important steps we need to know)
[RedisInsight Docker image](https://hub.docker.com/r/redislabs/redisinsight/tags) tag 1.12.1

**Steps to reproduce** (How to reproduce what you found step by step)
1. Deploy as per redisinsight document about [installation in Kubernetes](https://docs.redis.com/latest/ri/installing/install-k8s/), while the latest tag equals tag 1.12.1
2. Create an ingress of aws alb class, and config https annotations, while redisinsight is the backend
3. Browse the https url and add a redis database
4. Do add key or delete key / Turn to CLI menu to run command / change right corner settings

**Actual behavior** (A short description of what you found)
Cannot do the above Step 4 operation, request is denied with status code 403 and response "CSRF Failed: Origin checking failed ..."
Does not meet this issue with 1.11.1 or 1.12.0
![image](https://user-images.githubusercontent.com/93997542/178502842-a620bc61-5a2d-434a-b7c8-61c8f469d5dc.png)

**Expected behavior** (A short description of what you expected to find)
All operation works

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ewoelfel** [comment]
I also experienced this error. Reverting to 1.11.1 helped resolving the issue for now. The reason seems to be that the django framework checks the trusted origins (see https://docs.djangoproject.com/en/4.0/ref/settings/#csrf-trusted-origins)
I also tried using the new redis insight 2.0 GA which did not have the CSRF-Issue however i experienced timeouts resolving the cluster

**Comment by GnaneshKunal** [comment]
@kyleli666 

I'm looking into the issue. Can you also meanwhile check if the proxy is setup right?

Here's an nginx one: https://stackoverflow.com/a/19593849/6830396

**Comment by kyleli666** [comment]
@GnaneshKunal Thank you.
I'm not using nginx, but AWS ALB formed by Ingress in k8s.
I don't have issue on version 1.11.1 with my proxy setup, is there something new need attetion from 1.12?
Here is my ingress declaration,
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redisinsight-ingress
  namespace: manage-tool
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: qa-manage-tool
    alb.ingress.kubernetes.io/group.name: manage-tool
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 83}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
  labels:
    app: redisinsight
spec:
  ingressClassName: alb
  rules:
    - host: "*.mydomain.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redisinsight-service
                port:
                  number: 80
```
