### ISSUE TITLE
[Bug]: Browser page becomes unresponsive / slow loading

### ISSUE THREAD

**Issue by juventus18** [RedisInsight/RedisInsight#949]
**Preconditions** (Any important steps we need to know)
none.

**Steps to reproduce** (How to reproduce what you found step by step)
When using the key browser to view values, if there is a field with a large value (say, an image as hex string  ~300kb) the page takes a long time to load (~30s) or sometimes becomes unresponsive.

**Actual behavior** (A short description of what you found)
The page sometimes crashes or otherwise takes a long time to load.

**Expected behavior** (A short description of what you expected to find)
The page should not crash

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
Page unresponsive
![image](https://user-images.githubusercontent.com/1124513/180079749-414a2420-5030-49db-b7bd-2afcdfb62027.png)

Sample view (redacted)
![image](https://user-images.githubusercontent.com/1124513/180080791-7212a2a0-ff02-4f82-a41a-61e5f91a2cd4.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
running from docker image `:latest` tag against redis 4.x.x (also running under docker)

**Comment by suiwenfeng** [comment]
browser is blocking at Layout for long time while rendering, and the layout recalculation caused by font.
``` css
.stringValue {
  font: inherit !important; // remove this line will fix the issue.
  color: inherit !important;
  padding: 0 !important;
  background: inherit !important;
}
```
